# Generated by Django 4.2.11 on 2024-07-07 10:49

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_alter_recruitmentpost_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('information', models.TextField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('company_type', models.IntegerField(blank=True, choices=[(0, 'Công ty TNHH'), (1, 'Công ty Cổ phần'), (2, 'Công ty tư nhân')], null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('title', models.CharField(max_length=255)),
                ('deadline', models.DateField()),
                ('quantity', models.IntegerField()),
                ('gender', models.IntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female'), (2, 'Both male and female')], default=0, null=True)),
                ('location', models.CharField(max_length=255)),
                ('salary', models.IntegerField()),
                ('position', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('experience', models.CharField(max_length=255)),
                ('reported', models.BooleanField(blank=True, default=False, null=True)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='jobs.area')),
                ('career', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='jobs.career')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.company')),
                ('companytype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='jobs.companytype')),
            ],
            options={
                'ordering': ['deadline', 'id'],
                'unique_together': {('company', 'title')},
            },
        ),
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('salary_expectation', models.IntegerField()),
                ('experience', models.TextField(blank=True, null=True)),
                ('cv', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='cv')),
                ('areas', models.ManyToManyField(blank=True, to='jobs.area')),
                ('career', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='jobs.career')),
                ('skills', models.ManyToManyField(blank=True, to='jobs.skill')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='areas',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='career',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='recruitmentpost',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='recruitmentpost',
            name='area',
        ),
        migrations.RemoveField(
            model_name='recruitmentpost',
            name='career',
        ),
        migrations.RemoveField(
            model_name='recruitmentpost',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='recruitmentpost',
            name='employmenttype',
        ),
        migrations.RemoveField(
            model_name='savedpost',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='savedpost',
            name='requirement_post',
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='coverLetter',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='recruitment',
        ),
        migrations.RemoveField(
            model_name='status',
            name='active',
        ),
        migrations.RemoveField(
            model_name='status',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='status',
            name='updated_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_applicant',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_employer',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='jobSeeker', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female'), (2, 'Both male and female')], null=True),
        ),
        migrations.DeleteModel(
            name='EmploymentType',
        ),
        migrations.DeleteModel(
            name='SavedPost',
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='comment',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.company'),
        ),
        migrations.AddField(
            model_name='comment',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
        ),
        migrations.AddField(
            model_name='comment',
            name='jobSeeker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.jobseeker'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='jobs.job'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='jobSeeker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='jobs.jobseeker'),
        ),
        migrations.AddField(
            model_name='like',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.company'),
        ),
        migrations.AddField(
            model_name='like',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
        ),
        migrations.AddField(
            model_name='like',
            name='jobSeeker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.jobseeker'),
        ),
        migrations.AddField(
            model_name='rating',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.company'),
        ),
        migrations.AddField(
            model_name='rating',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
        ),
        migrations.AddField(
            model_name='rating',
            name='jobSeeker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.jobseeker'),
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('job', 'jobSeeker')},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('jobSeeker', 'job'), ('company', 'job')},
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('jobSeeker', 'job'), ('company', 'job')},
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='recruitment',
        ),
        migrations.RemoveField(
            model_name='like',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='like',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='like',
            name='recruitment',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='recruitment',
        ),
        migrations.DeleteModel(
            name='Applicant',
        ),
        migrations.DeleteModel(
            name='Employer',
        ),
        migrations.DeleteModel(
            name='RecruitmentPost',
        ),
    ]
