# Generated by Django 4.2.11 on 2024-07-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0023_alter_job_salary_alter_jobseeker_salary_expectation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['created_date', 'id']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='jobSeeker',
            new_name='jobseeker',
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='jobSeeker',
            new_name='jobseeker',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='jobSeeker',
            new_name='jobseeker',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='jobSeeker',
            new_name='jobseeker',
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('job', 'jobseeker')},
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='is_student',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='comment',
            field=models.CharField(default='No comment', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(blank=True, choices=[(0, 'Applicant'), (1, 'Employer')], null=True),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('company', 'job'), ('jobseeker', 'job')},
        ),
    ]
