# Generated by Django 4.2.11 on 2024-08-03 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0024_alter_jobapplication_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotification',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='usernotification',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='UserNotification',
        ),
    ]
